apiVersion: apps/v1
kind: Deployment
metadata:
  name: itemstock-app
  namespace: itemstock
  labels:
    app: itemstock
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: itemstock
  template:
    metadata:
      labels:
        app: itemstock
    spec:
      containers:
        - name: itemstock
          image: itemstock:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8501
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 90
            periodSeconds: 30
            failureThreshold: 3
