apiVersion: apps/v1
kind: Deployment
metadata:
  name: itemstock-app
  namespace: itemstock
  labels:
    app: itemstock
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: itemstock
  template:
    metadata:
      labels:
        app: itemstock
    spec:
      containers:
        - name: itemstock
          image: itemstock:latest
          imagePullPolicy: Never
          env:
            - name: SQLITE_PATH
              value: /app/data/app.db
          volumeMounts:
            - name: itemstock-data
              mountPath: /app/data
          ports:
            - containerPort: 8501
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 40
            periodSeconds: 20
            failureThreshold: 3
      volumes:
        - name: itemstock-data
          persistentVolumeClaim:
            claimName: itemstock-data-pvc
